namespace Proximity.Core.Interfaces;

/// <summary>
/// Interface for audio encoding and decoding (e.g., Opus codec)
/// </summary>
public interface IAudioCodec : IDisposable
{
    /// <summary>
    /// Encode PCM samples to compressed audio data
    /// </summary>
    /// <param name="pcmSamples">Input PCM samples (16-bit signed)</param>
    /// <param name="sampleCount">Number of samples to encode</param>
    /// <returns>Compressed audio bytes</returns>
    byte[] Encode(short[] pcmSamples, int sampleCount);

    /// <summary>
    /// Decode compressed audio data back to PCM samples
    /// </summary>
    /// <param name="encodedData">Compressed audio bytes</param>
    /// <param name="encodedLength">Number of bytes in the encoded data</param>
    /// <returns>Decoded PCM samples (16-bit signed)</returns>
    short[] Decode(byte[] encodedData, int encodedLength);

    /// <summary>
    /// Generate concealment audio for a lost packet (Packet Loss Concealment)
    /// </summary>
    /// <returns>PCM samples generated by PLC</returns>
    short[] DecodePLC();

    /// <summary>
    /// Number of samples per frame (e.g., 960 for 20ms @ 48kHz)
    /// </summary>
    int FrameSize { get; }

    /// <summary>
    /// Sample rate in Hz
    /// </summary>
    int SampleRate { get; }

    /// <summary>
    /// Number of channels
    /// </summary>
    int Channels { get; }
}
